---
- name: pi wifi restart
  hosts: localhost
  remote_user: root
  gather_facts: false

  tasks:
  - name: ping google dns
    shell: ping 8.8.8.8

  - name: ping local router
    shell: ping 192.168.1.254
